package controleclientes;

import javax.swing.JOptionPane;

public class telaPrinc extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telaPrinc.class.getName());

    /**
     * Creates new form telaPrinc
     */
    public telaPrinc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTroca = new javax.swing.JPanel();
        painelInicial = new javax.swing.JPanel();
        tituloCC = new javax.swing.JLabel();
        unifagocLogo = new javax.swing.JLabel();
        painelCadastro = new javax.swing.JPanel();
        nomeC = new javax.swing.JLabel();
        cpfC = new javax.swing.JLabel();
        idadeC = new javax.swing.JLabel();
        txtNC = new javax.swing.JTextField();
        txtCCpf = new javax.swing.JTextField();
        txtCIdd = new javax.swing.JTextField();
        cadastro = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCanc = new javax.swing.JButton();
        menuBarPrincipal = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        Novo = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        Cliente = new javax.swing.JMenuItem();
        Fonecedor = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();
        Info = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU, ITENS DE MENU, FONTES");
        setPreferredSize(new java.awt.Dimension(600, 400));

        painelTroca.setPreferredSize(new java.awt.Dimension(340, 100));
        painelTroca.setLayout(new java.awt.CardLayout());

        painelInicial.setBackground(new java.awt.Color(255, 255, 0));
        painelInicial.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 20, 1));

        tituloCC.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        tituloCC.setForeground(new java.awt.Color(0, 102, 51));
        tituloCC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloCC.setText("CONTROLE DE CLIENTES");

        unifagocLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unifagocLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unifagoc.PNG"))); // NOI18N
        unifagocLogo.setPreferredSize(new java.awt.Dimension(120, 120));

        javax.swing.GroupLayout painelInicialLayout = new javax.swing.GroupLayout(painelInicial);
        painelInicial.setLayout(painelInicialLayout);
        painelInicialLayout.setHorizontalGroup(
            painelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInicialLayout.createSequentialGroup()
                .addGroup(painelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelInicialLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(tituloCC))
                    .addGroup(painelInicialLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(unifagocLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelInicialLayout.setVerticalGroup(
            painelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInicialLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(tituloCC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(unifagocLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelTroca.add(painelInicial, "card2");

        painelCadastro.setBackground(new java.awt.Color(255, 255, 255));
        painelCadastro.setRequestFocusEnabled(false);

        nomeC.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        nomeC.setForeground(new java.awt.Color(0, 0, 0));
        nomeC.setText("Nome do cliente: ");

        cpfC.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cpfC.setForeground(new java.awt.Color(0, 0, 0));
        cpfC.setText("CPF: ");

        idadeC.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        idadeC.setForeground(new java.awt.Color(0, 0, 0));
        idadeC.setText("Idade:");

        txtNC.setColumns(20);
        txtNC.setToolTipText("");
        txtNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNCActionPerformed(evt);
            }
        });

        txtCCpf.setColumns(20);

        txtCIdd.setColumns(20);

        cadastro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cadastro.setForeground(new java.awt.Color(0, 0, 0));
        cadastro.setText("Cadastro");

        btnSalvar.setBackground(new java.awt.Color(0, 255, 0));
        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCanc.setBackground(new java.awt.Color(255, 0, 0));
        btnCanc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCanc.setForeground(new java.awt.Color(255, 255, 255));
        btnCanc.setText("Cancelar");
        btnCanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCadastroLayout = new javax.swing.GroupLayout(painelCadastro);
        painelCadastro.setLayout(painelCadastroLayout);
        painelCadastroLayout.setHorizontalGroup(
            painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastroLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addComponent(nomeC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addComponent(cpfC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastroLayout.createSequentialGroup()
                        .addComponent(idadeC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCIdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
            .addGroup(painelCadastroLayout.createSequentialGroup()
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnCanc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(cadastro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelCadastroLayout.setVerticalGroup(
            painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(cadastro)
                .addGap(30, 30, 30)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeC, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfC)
                    .addComponent(txtCCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCIdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idadeC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCanc, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
        );

        painelTroca.add(painelCadastro, "card3");

        menuArquivo.setText("Arquivo");

        Novo.setText("Novo");
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });
        menuArquivo.add(Novo);

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        menuArquivo.add(Sair);

        menuBarPrincipal.add(menuArquivo);

        menuRelatorio.setText("Relatório");

        Cliente.setText("Clientes");
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });
        menuRelatorio.add(Cliente);

        Fonecedor.setText("Fornecedores");
        Fonecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FonecedorActionPerformed(evt);
            }
        });
        menuRelatorio.add(Fonecedor);

        menuBarPrincipal.add(menuRelatorio);

        menuSobre.setText("Sobre");

        Info.setText("Info");
        Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoActionPerformed(evt);
            }
        });
        menuSobre.add(Info);

        menuBarPrincipal.add(menuSobre);

        setJMenuBar(menuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTroca, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTroca, javax.swing.GroupLayout.PREFERRED_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNCActionPerformed

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed
    java.awt.CardLayout cl = (java.awt.CardLayout) painelTroca.getLayout();
    cl.show(painelTroca, "card3");     }//GEN-LAST:event_NovoActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        System.exit(0);    }//GEN-LAST:event_SairActionPerformed

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
    JOptionPane.showMessageDialog(this, "Relatório de clientes");
    }//GEN-LAST:event_ClienteActionPerformed

    private void FonecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FonecedorActionPerformed
    JOptionPane.showMessageDialog(this, "Relatório de fornecedores");

    }//GEN-LAST:event_FonecedorActionPerformed

    private void InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoActionPerformed
    JOptionPane.showMessageDialog(this, "Aluno(a): Lorena Prudencio Ferreira\nCiencia da Computacao UNIFAGOC\n6 Periodo");
    }//GEN-LAST:event_InfoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
    JOptionPane.showMessageDialog(this, "Cliente salvo com sucesso!");
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancActionPerformed
    java.awt.CardLayout cl = (java.awt.CardLayout) painelTroca.getLayout();
    cl.show(painelTroca, "card2");
    }//GEN-LAST:event_btnCancActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new telaPrinc().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cliente;
    private javax.swing.JMenuItem Fonecedor;
    private javax.swing.JMenuItem Info;
    private javax.swing.JMenuItem Novo;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JButton btnCanc;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel cadastro;
    private javax.swing.JLabel cpfC;
    private javax.swing.JLabel idadeC;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuBar menuBarPrincipal;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JLabel nomeC;
    private javax.swing.JPanel painelCadastro;
    private javax.swing.JPanel painelInicial;
    private javax.swing.JPanel painelTroca;
    private javax.swing.JLabel tituloCC;
    private javax.swing.JTextField txtCCpf;
    private javax.swing.JTextField txtCIdd;
    private javax.swing.JTextField txtNC;
    private javax.swing.JLabel unifagocLogo;
    // End of variables declaration//GEN-END:variables
}
